name: Publish Docker image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_push:
    name: Build and Push Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Get the commit message
        run: echo "commit_message=$(git log --format=%B -n 1 ${{ github.sha }})" >> $GITHUB_ENV

      - name: Generate image tag from commit message
        id: generate_tag
        run: echo "tag=$(echo ${{ env.commit_message }} | tr -d '[:space:]' | tr -d [:punct:])" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t mahamed1/my-react-app:${{ env.tag }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'docker.io/mahamed1/my-react-app:${{ env.tag }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Push Docker image to Docker Hub
        run: docker push mahamed1/my-react-app:${{ env.tag }}

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
