name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Hier kun je de gewenste tag genereren op basis van de commit-informatie
      - name: Get commit message
        id: commit_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.sha }})"
      
      - name: Generate image tag
        id: generate_tag
        run: echo "::set-output name=tag::$(echo ${{ steps.commit_message.outputs.message }} | cut -d ' ' -f 1)"

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/my-organization/my-app:${{ steps.generate_tag.outputs.tag }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.io/my-organization/my-app:${{ steps.generate_tag.outputs.tag }}
