name: Publish Docker image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_push:
    name: Build and Push Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Get the short commit SHA
        id: vars
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build -t mahamed1/my-react-app:${{ env.short_sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'docker.io/mahamed1/my-react-app:${{ env.short_sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Push Docker image to Docker Hub
        run: docker push mahamed1/my-react-app:${{ env.short_sha }}

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
